services:
  db:
    build: ../test-03-database
    container_name: operadoras_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: api_operadoras
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/operadoras
    ports:
      - "8000:8000"

  backend-test:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/operadoras
    command: pytest

  frontend:
    build: ./frontend
    container_name: frontend_operadoras
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  frontend-test:
    build: ./frontend
    container_name: frontend_tests
    command: npm run test
    depends_on:
      - backend

volumes:
  db_data:
